name: Appium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Start Android Emulator
    runs-on: macos-latest
    # env:
    #   ANDROID_ARCH: x86
    #   ANDROID_TARGET: default
    #   API_LEVEL: 29
    #   EMULATOR_TIMEOUT: 500
    #   EMULATOR_NAME: Nexus 5
    #   JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64
    #   ANDROID_HOME: /usr/local/lib/android/sdk
    #   ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up JDK
    #   uses: actions/setup-java@v2
    #   with:
    #     distribution: 'temurin'
    #     java-version: '17'
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86
        profile: Nexus 5
        heap-size: 2048
        emulator-options: -accel auto -no-snapshot -no-window
        script: echo "Generated AVD snapshot for caching."
        
    # - name: Setup Android SDK
    #   uses: android-actions/setup-android@v3

    # - name: Available SDK packages in Android SDK
    #   run: sdkmanager --list | grep system-images

    # - name: Print Package Path
    #   run: echo "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

    # - name: Install SDK System Image
    #   run: sdkmanager --install "system-images;android-29;google_apis;x86"
        
    # - name: Print System Images Path
    #   run: echo "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
    #   env:
    #     API_LEVEL: ${{ env.API_LEVEL }}
    #     ANDROID_TARGET: ${{ env.ANDROID_TARGET }}
    #     ANDROID_ARCH: ${{ env.ANDROID_ARCH }}

    # - name: Check Android SDK directory
    #   run: ls -l $ANDROID_HOME

    # - name: Start Android Emulator
    #   uses: reactivecircus/android-emulator-runner@v2
    #   with:
    #     api-level: 29
    #     target: default
    #     arch: x86
    #     profile: Nexus 5
    #     heap-size: 2048
    #     emulator-options: -accel auto -no-snapshot -no-window

    - name: List ADB Devices
      run: adb devices

    - name: Install Dependencies
      run: mvn install --quiet

    - name: Build and Test with Maven
      run: mvn clean verify --quiet

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium@latest

    - name: Install uiautomator2
      run: appium driver install uiautomator2

    - name: Print Appium Version
      run: appium -v

    - name: Install ChromeDriver
      run: |
        LATEST_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -O "https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Appium Server
      run: appium & sleep 20

    - name: Run Appium Tests
      run: mvn -B clean test -Dtest=PatientTests#verifyThatCanLogoutSuccessfullyFromTheApp
