name: Appium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Check sdk list
      run: |
        avdmanager list avd
        sdkmanager --list
    - name: Build emulator
      run: |
        echo "no" | avdmanager create avd --force --name "nexus" --package "system-images;android-33;google_apis_playstore;x86_64" --abi x86_64      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium@latest

    - name: Install uiautomator2
      run: appium driver install uiautomator2
      
    - name: Print Appium Version
      run: appium -v

    - name: Install ChromeDriver
      run: |
        LATEST_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -O "https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Appium Server
      run: appium & sleep 20

    - name: Run Appium Tests
      run: mvn -B clean test -Dtest=PatientTests#verifyThatCanLogoutSuccessfullyFromTheApp
