name: Appium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Start Android Emulator
    runs-on: ubuntu-latest
        
    steps:        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      run: sudo apt-get install openjdk-17-jdk

    - name: Setup Android SDK
      run: |
        wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz
        tar -xvf android-sdk_r24.2-linux.tgz
        cd android-sdk-linux/tools && ls -l
    
    - name: Install SDK Command-line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        mkdir sdkmanager_temp
        cd sdkmanager_temp
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        mv cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/
        cd ..
        rm -rf sdkmanager_temp

    - name: Set Android SDK Root
      run: echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV

    - name: List bin data
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/bin/

    - name: List lib data
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/lib/
        
    - name: Install Android SDK Packages
      run: |
        export PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/bin
        yes | sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
        sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "build-tools;23.0.2" "platforms;android-23"
        sdkmanager --sdk_root=$HOME/Android/Sdk --update


    - name: list system images in sdk
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager

    - name: Install Android Images
      run: |
        avdmanager create avd -n my_avd_name -k "system-images;android-23;google_apis;x86_64"

    - name: Add Android Platform to Ionic
      run: ionic platform add android
    
    - name: Run Emulator
      run: emulator -avd my_avd_name -no-window -no-audio
