name: Appium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean test

    - name: Start Appium Server
      run: appium

    - name: Run Appium Tests
      run: mvn -B verify -Dtest=PatientTests#verifyThatCanLogoutSuccessfullyFromTheApp
