name: Appium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Start Android Emulator
    runs-on: ubuntu-latest
        
    steps:        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      run: sudo apt-get install openjdk-17-jdk

    - name: Setup Android SDK
      run: |
        wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz
        tar -xvf android-sdk_r24.2-linux.tgz
        cd android-sdk-linux/tools && ls -l
    
    - name: Install SDK Command-line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        mkdir sdkmanager_temp
        cd sdkmanager_temp
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        mv cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/
        cd ..
        rm -rf sdkmanager_temp

    - name: List Available Packages
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/

    - name: List bin data
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/bin/

    - name: List lib data
      run: |
        ls -l $HOME/Android/Sdk/cmdline-tools/lib/
    
    - name: Install Android SDK Packages
      run: |
        cd $HOME/Android/cmdline-tools/tools/bin
        ./android update sdk --no-ui --all --filter "platform-tools,build-tools-23.0.2,android-23"

    - name: Set PATH in ~/.bashrc
      run: echo 'export PATH=${PATH}:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/tools:$HOME/Android/Sdk/build-tools/23.0.2/' >> ~/.bashrc

    - name: Install Desired Android Platforms
      run: $HOME/Android/Sdk/tools/android sdk
    
    - name: Install Android Images
      run: $HOME/Android/Sdk/tools/android avd
    
    - name: Add Android Platform to Ionic
      run: ionic platform add android
    
    - name: Run Emulator
      run: ionic emulate android

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium@latest

    - name: Install uiautomator2
      run: appium driver install uiautomator2

    - name: Print Appium Version
      run: appium -v

    - name: Install ChromeDriver
      run: |
        LATEST_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -O "https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Appium Server
      run: appium & sleep 20

    - name: Run Appium Tests
      run: mvn -B clean test -Dtest=PatientTests#verifyThatCanLogoutSuccessfullyFromTheApp
