name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      Denv: "-Denv=STAGE"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B surefire-report:report ${{ env.Denv }} test
    
    # Add a step to list the contents of the directory for debugging
    - name: List Directory Contents
      run: ls -l
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: "**/Screenshot"
